// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByZp9dCPLRXZkAgw0sCV6uvptMt3KCSmQ',
    appId: '1:464161445635:web:d08b607d7f5eca53093b36',
    messagingSenderId: '464161445635',
    projectId: 'loginappbusinexperts',
    authDomain: 'loginappbusinexperts.firebaseapp.com',
    storageBucket: 'loginappbusinexperts.appspot.com',
    measurementId: 'G-JGB138J6H6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL20gCeEArrPkdY4xpiwiBVmua2eEPCCo',
    appId: '1:464161445635:android:b2d03660cb35aa57093b36',
    messagingSenderId: '464161445635',
    projectId: 'loginappbusinexperts',
    storageBucket: 'loginappbusinexperts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKf48qnme7t1YElhMzk943q-5PUVjUMiw',
    appId: '1:464161445635:ios:f916006f96ff70a6093b36',
    messagingSenderId: '464161445635',
    projectId: 'loginappbusinexperts',
    storageBucket: 'loginappbusinexperts.appspot.com',
    iosBundleId: 'com.example.loginapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKf48qnme7t1YElhMzk943q-5PUVjUMiw',
    appId: '1:464161445635:ios:0fb8fde945923366093b36',
    messagingSenderId: '464161445635',
    projectId: 'loginappbusinexperts',
    storageBucket: 'loginappbusinexperts.appspot.com',
    iosBundleId: 'com.example.loginapp.RunnerTests',
  );
}
